import type { WabaAccount, PhoneNumber, PagedResponse } from "./page";

// NOTE: export the interfaces from page.tsx (add `export` to them) so this file can reuse them,
// or copy the type shapes here if you prefer to keep page.tsx untouched.

export const mockWabaPage: PagedResponse<WabaAccount> = {
  offset: 0,
  limit: 10,
  length: 3,
  items: [
    {
      id: "1191809157345209",
      name: "Support",
      currency: "IDR",
      messageTemplateNamespace: "57d3478f_4d00_4ed3_a3a8_c09ffdbbada5",
      accountReviewStatus: "APPROVED",
      businessId: "1552111603299862",
      businessStatus: "APPROVED",
      businessName: "Saffron Market",
      businessVerificationStatus: "verified",
      whatsappBusinessManagerMessagingLimit: "TIER_2K",
      ownershipType: "CLIENT_OWNED",
      primaryFundingId: "27501969222825098",
      timezoneId: "71",
      paymentMethodAttached: true,
      isOnBizApp: false,
    },
    {
      id: "1483159693564497",
      name: "Saffron Market",
      currency: "IDR",
      messageTemplateNamespace: "713b9b10_3bd0_432c_84b2_5d4ff6f2e7a5",
      accountReviewStatus: "APPROVED",
      businessId: "1552111603299862",
      businessStatus: "APPROVED",
      businessName: "Saffron Market",
      businessVerificationStatus: "verified",
      whatsappBusinessManagerMessagingLimit: "TIER_2K",
      ownershipType: "CLIENT_OWNED",
      primaryFundingId: "27501969222825098",
      timezoneId: "71",
      paymentMethodAttached: true,
      isOnBizApp: false,
    },
    {
      id: "9988776655443322",
      name: "Acme Sales",
      currency: "USD",
      messageTemplateNamespace: "aa11bb22_cc33_dd44_ee55_ff6677889900",
      accountReviewStatus: "PENDING",
      businessId: "7001234500099999",
      businessStatus: "APPROVED",
      businessName: "Acme Corporation",
      businessVerificationStatus: "not_verified",
      whatsappBusinessManagerMessagingLimit: "TIER_1K",
      ownershipType: "CLIENT_OWNED",
      primaryFundingId: "30001112223334445",
      timezoneId: "1",
      paymentMethodAttached: false,
      isOnBizApp: false,
    },
  ],
};

export const mockPhonePage: PagedResponse<PhoneNumber> = {
  offset: 0,
  limit: 10,
  length: 5,
  items: [
    // WABA "Support" -> 2 numbers (demonstrates multi-number arrangement)
    {
      id: "1140615095809542",
      phoneNumber: "+17174300078",
      wabaId: "1191809157345209",
      verifiedName: "Support",
      qualityRating: "GREEN",
      messagingLimit: "TIER_2K",
      whatsappBusinessManagerMessagingLimit: "TIER_2K",
      isOfficialBusinessAccount: false,
      codeVerificationStatus: "VERIFIED",
      status: "CONNECTED",
      displayPhoneNumber: "+1 717-430-0078",
      nameStatus: "APPROVED",
      newNameStatus: "NONE",
      decision: "APPROVED",
      requestedVerifiedName: "Support",
      isOnBizApp: false,
    },
    {
      id: "1140615095809999",
      phoneNumber: "+17174300099",
      wabaId: "1191809157345209",
      verifiedName: "Support Backup",
      qualityRating: "YELLOW",
      messagingLimit: "TIER_2K",
      whatsappBusinessManagerMessagingLimit: "TIER_2K",
      isOfficialBusinessAccount: false,
      codeVerificationStatus: "VERIFIED",
      status: "PENDING",
      displayPhoneNumber: "+1 717-430-0099",
      nameStatus: "PENDING",
      newNameStatus: "NONE",
      decision: "PENDING",
      requestedVerifiedName: "Support Backup",
      isOnBizApp: false,
    },
    // WABA "Saffron Market" -> 1 number
    {
      id: "1192439530612497",
      phoneNumber: "+15559107968",
      wabaId: "1483159693564497",
      verifiedName: "Saffron Market",
      qualityRating: "GREEN",
      messagingLimit: "TIER_2K",
      whatsappBusinessManagerMessagingLimit: "TIER_2K",
      isOfficialBusinessAccount: false,
      codeVerificationStatus: "VERIFIED",
      status: "CONNECTED",
      displayPhoneNumber: "+1 555-910-7968",
      nameStatus: "DECLINED",
      newName: "Learning and Tutorials",
      newNameStatus: "DECLINED",
      decision: "REJECTED",
      requestedVerifiedName: "Learning and Tutorials",
      rejectionReason: "BIZ_COMMERCE_VIOLATION_OTHER",
      isOnBizApp: false,
    },
    // WABA "Acme Sales" -> 2 numbers (second business, also multi-number)
    {
      id: "2233445566778899",
      phoneNumber: "+442079460001",
      wabaId: "9988776655443322",
      verifiedName: "Acme Sales UK",
      qualityRating: "GREEN",
      messagingLimit: "TIER_1K",
      whatsappBusinessManagerMessagingLimit: "TIER_1K",
      isOfficialBusinessAccount: false,
      codeVerificationStatus: "VERIFIED",
      status: "CONNECTED",
      displayPhoneNumber: "+44 20 7946 0001",
      nameStatus: "APPROVED",
      newNameStatus: "NONE",
      decision: "APPROVED",
      requestedVerifiedName: "Acme Sales UK",
      isOnBizApp: false,
    },
    {
      id: "2233445566770000",
      phoneNumber: "+442079460002",
      wabaId: "9988776655443322",
      verifiedName: "Acme Sales EU",
      qualityRating: "RED",
      messagingLimit: "TIER_1K",
      whatsappBusinessManagerMessagingLimit: "TIER_1K",
      isOfficialBusinessAccount: false,
      codeVerificationStatus: "NOT_VERIFIED",
      status: "INACTIVE",
      displayPhoneNumber: "+44 20 7946 0002",
      nameStatus: "PENDING",
      newNameStatus: "NONE",
      decision: "PENDING",
      requestedVerifiedName: "Acme Sales EU",
      isOnBizApp: false,
    },
  ],
};